### ISSUE TITLE
Library cannot be compiled on Windows

### ISSUE THREAD

**Issue by JuxhinDB** [jedisct1/rust-geoip#13]
Current the use of [`std::os::unix::*`](https://github.com/jedisct1/rust-geoip/blob/862c25d123b9c7398b109e029431ce5813831f61/src/geoip/lib.rs#L15) does not allow this library to be used on any Windows. 

When trying to use this in twistrs, we get the following compile-time error:

```
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> .cargo\registry\src\github.com-1ecc6299db9ec823\geoip-0.0.13\src/geoip/lib.rs:16:14
   |
16 | use std::os::unix::ffi::OsStrExt;
   |              ^^^^ could not find `unix` in `os`

error[E0599]: no method named `as_bytes` found for reference `&std::ffi::OsStr` in the current scope
   --> .cargo\registry\src\github.com-1ecc6299db9ec823\geoip-0.0.13\src/geoip/lib.rs:286:52
    |
286 |                 ffi::CString::new(path.as_os_str().as_bytes())?.as_ptr(),
    |                                                    ^^^^^^^^ method not found in `&std::ffi::OsStr
```

Let me know if you would like me to push a PR to address this.

**Comment by jedisct1** [comment]
Sure, a PR would be more than welcome!

**Comment by zhiyong0804** [comment]
i change std::os::unix::ffi::OsStrExt to std::os::windows::ffi::OsStrExt and fix compile first compile error, but when i still donot know how fix seconed error, could you fix it?

**Comment by zhiyong0804** [comment]
i have fix the compile errors on windows platform, you can see : https://github.com/zhiyong0804/rust-geoip
